name: flutter_inappwebview
description: A Flutter plugin that allows you to add an inline webview, to use an headless webview, and to open an in-app browser window.
version: 5.3.2
homepage: https://github.com/pichillilorenzo/flutter_inappwebview

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.22.2"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.1

flutter:
  plugin:
    platforms:
      android:
        package: com.pichillilorenzo.flutter_inappwebview
        pluginClass: InAppWebViewFlutterPlugin
      ios:
        pluginClass: InAppWebViewFlutterPlugin
  assets:
    - packages/flutter_inappwebview/t_rex_runner/t-rex.html
    - packages/flutter_inappwebview/t_rex_runner/t-rex.css